name: carrentino_v2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.0
  freezed: ^3.0.3
  go_router: ^14.8.1
  standard_searchbar: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts: 
    - family: Manrope
      fonts:
       - asset: assets\font\Manrope-ExtraLight.ttf
         weight: 200
       - asset: assets\font\Manrope-Light.ttf
         weight: 300
       - asset: assets\font\Manrope-Regular.ttf
         weight: 400
       - asset: assets\font\Manrope-Medium.ttf
         weight: 500
       - asset: assets\font\Manrope-SemiBold.ttf
         weight: 600
       - asset: assets\font\Manrope-Bold.ttf
         weight: 700
       - asset: assets\font\Manrope-ExtraBold.ttf
         weight: 800
  assets:
    - assets/nav_bar/
    - assets/main_screen/
